### ISSUE TITLE
Multiple bundles are not attached

### ISSUE THREAD

**Issue by EvgheniAnachii** [micro-frontends-demo/container#16]
I run in a case when my "browse" micro frontend has its own route and inside that project, I load bundles dynamically based on the route I select (lazy loading), however, it's not true in case I want my project to be included as a micro frontend.
For now, let's say my "Browse" app has the following inside its manifest.json:
`{
  "main.css": "/main.css",
  "main.js": "/main.5d78560c5d4d6ccb90a6.js",
  "main.css.map": "/main.css.map",
  "main.js.map": "/main.5d78560c5d4d6ccb90a6.js.map",
  "1.5d78560c5d4d6ccb90a6.js": "/1.5d78560c5d4d6ccb90a6.js",
  "1.5d78560c5d4d6ccb90a6.js.map": "/1.5d78560c5d4d6ccb90a6.js.map",
  "2.5d78560c5d4d6ccb90a6.js": "/2.5d78560c5d4d6ccb90a6.js",
  "2.5d78560c5d4d6ccb90a6.js.map": "/2.5d78560c5d4d6ccb90a6.js.map",
  "index.html": "/index.html"
}`

Based on the logic inside the Microfrontend component, I extract only main.js which represents my home page for "Browse" project, but once I get to the second "page" of "Browse" app, it throws an error that it cannot find 1.5d78560c5d4d6ccb90a6.js and so on...

**Comment by camjackson** [comment]
Yes, this is an unsolved problem. The easiest thing to do is to not do lazy loading, and disable chunking, which I did with this rewiring: https://github.com/camjackson/react-app-rewire-micro-frontends.

In theory it should be possible to change the [bundle loading code](https://github.com/micro-frontends-demo/container/blob/master/src/MicroFrontend.js#L13-L22) so that it's smart enough to download whatever needs to be downloaded. I had a brief attempt at it when creating the demo but ultimately decided it wasn't worth the effort for the sake of a simple demo.

It might be worth having a look at the upcoming Module Federation feature in webpack, which will add native support to webpack for dynamically importing modules from independently compiled webpack bundles.

**Comment by ScriptedAlchemy** [comment]
yep Module Federation was designed to do this, keeps SPA's standalone capable but also works like at runtime npm registry generated by your module federation and your own dependencies.  

https://github.com/module-federation/module-federation-examples
https://github.com/sokra/slides/blob/master/content/ModuleFederationWebpack5.md
